name: RescaleAllImages
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Install pillow
        run: pip install pillow
      - name: Rescale images
        run: python -m afol_toolbox_app.static.img.img_scaler
      - name: Configure git and add files
        run: |
          git config --global user.name 'bb1950328'
          git config --global user.email 'bb1950328@gmail.com'
          git add afol_toolbox_app/static/img
      - name: Commit if something changed
        run: ./.github/workflows/commit_if_changed.sh
