name: RescaleAllImages
on: push
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
          architecture: x64
      - name: Install pillow
        run: pip install pillow
      - name: Rescale images
        run: python -m afol_toolbox_app.static.img.img_scaler
      - name: Configure git and add files
        run: |
          git config --global user.name 'bb1950328'
          git config --global user.email 'bb1950328@gmail.com'
          git add afol_toolbox_app/static/img
      - name: Check if something changed
        id: stage_check
        run: git diff --cached --quiet ::set-output name=status::success
        continue-on-error: true
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Commit changes
        if: steps.stage_check.outputs.status == 'failure' # exit code > 0 means something changed
        run: |
          git commit -am "Rescaled images (Github Action)"
          git push
