name: PythonUnittests

on: [push]

jobs:
  build:
    name: Python Unittests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: x64
    - name: install pip requirements
      run: pip install -r requirements.txt
    - name: Run the tests
      run: coverage run -m unittest discover -v afol_toolbox_app.test 2>&1 | tee ./unittest_output.txt
    - name: convert the coverage data
      run: coverage combine
    - name: Upload coverage data
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: Check Output
      run: |
        chmod a+x ./.github/workflows/compare_output.sh
        ./.github/workflows/compare_output.sh
