name: PythonUnittests

on: [push]

jobs:
  build:
    name: Python Unittests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: x64
    - name: Run the tests
      run: python -m unittest discover -v afol_toolbox_app.test | tee ./unittest_output.txt
    - name: Check Output
      run: |
        chmod a+x ./.github/workflows/compare_output.sh
        ./.github/workflows/compare_output.sh
