name: PythonUnittests

on: [push]

jobs:
  build:
    name: Python Unittests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run the tests
      run: python3.7 -m unittest discover /afol_toolbox_app/test | tee unittest_output.txt
